=== BillTheBest/voltdb/tests/sqlparser/tests/VoltXMLElementTestSuite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" 
           targetNamespace="http://www.voltdb.org" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xmlns:ns1="http://www.voltdb.org">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" />
    <xs:element name="VoltXMLElementTestSuite">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:tests"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tests">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:test"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="test">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:schema"/>
                <xs:element maxOccurs="unbounded" ref="ns1:testpoint"/>
            </xs:sequence>
            <xs:attribute name="classname" use="required"/>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="sourcefolder" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="schema">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:ddl"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ddl" type="xs:string"/>
    <xs:element name="testpoint">
        <xs:complexType>
        	<xs:attribute name="testKind" use="required"
        		type="xs:NCName" />
        	<xs:attribute name="testName" use="required"
        		type="xs:NCName" />
        	<xs:attribute name="comment" type="xs:string"></xs:attribute>
        	<xs:attribute name="testSQL" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BillTheBest/voltdb/tests/sqlparser/tests/SimpleTestSuite.xml
<?xml version="1.0" encoding="UTF-8" ?>
<VoltXMLElementTestSuite name="SimpleTestSuite"
    xmlns="http://www.voltdb.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.voltdb.org VoltXMLElementTestSuite.xsd">
    <tests>
        <test name="TestArithmeticExpression" sourcefolder="tests/sqlparser/tests" classname="org.voltdb.sqlparser.TestArithmeticExpressions">
            <schema>
                <ddl>create table alpha ( id integer, beta integer, gamma integer )</ddl>
                <ddl>create table gamma ( id integer not null, zooba integer )</ddl>
                <ddl>create table fargle ( id integer not null, dooba integer )</ddl>
            </schema>
            <testpoint testKind="dql" testName="TestSum"      testSQL="select * from alpha where id + id = 0"/>
            <testpoint testKind="dql" testName="TestDiff"     testSQL="select * from alpha where id - id = 0"/>
            <testpoint testKind="dql" testName="TestProd"     testSQL="select * from alpha where id * id = 0"/>
            <testpoint testKind="dql" testName="TestDiv"      testSQL="select * from alpha where id / id = 0"/>
            <testpoint testKind="dql" testName="TestSumProd"  testSQL="select * from alpha where id + beta * gamma = 0" />
            <testpoint testKind="dql" testName="TestProdSum"  testSQL="select * from alpha where id * beta + gamma = 0" />
            <testpoint testKind="dql" testName="TestSumDiv"   testSQL="select * from alpha where id + beta / gamma = 0" />
            <testpoint testKind="dql" testName="TestDivSum"   testSQL="select * from alpha where id / beta + gamma = 0" />
            <testpoint testKind="dql" testName="TestDiffProd" testSQL="select * from alpha where id - beta * gamma = 0" />
            <testpoint testKind="dql" testName="TestProdDiff" testSQL="select * from alpha where id * beta - gamma = 0" />
            <testpoint testKind="dql" testName="TestDiffDiv"  testSQL="select * from alpha where id - beta / gamma = 0" />
            <testpoint testKind="dql" testName="TestDivDiff"  testSQL="select * from alpha where id / beta - gamma = 0" />
            <testpoint testKind="dql" testName="TestSumDiff"  testSQL="select * from alpha where id + beta - gamma = 0" />
            <testpoint testKind="dql" testName="TestDiffSum"  testSQL="select * from alpha where id - beta + gamma = 0" />
            <testpoint testKind="dql" testName="TestProdDiv"  testSQL="select * from alpha where id * beta / gamma = 0" />
            <testpoint testKind="dql" testName="TestDivProd"  testSQL="select * from alpha where id / beta * gamma = 0" />
            <testpoint testKind="dql" testName="TestSumSum"   testSQL="select * from alpha where id + beta + gamma = 0" />
            <testpoint testKind="dql" testName="TestDiffDiff" testSQL="select * from alpha where id - beta - gamma = 0" />
            <testpoint testKind="dql" testName="TestProdProd" testSQL="select * from alpha where id * beta * gamma = 0" />
            <testpoint testKind="dql" testName="TestDivDiv"   testSQL="select * from alpha where id / beta / gamma = 0" />
        </test>
        <test name="TestBooleanOperators" sourcefolder="tests/sqlparser/tests" classname="org.voltdb.sqlparser.TestBooleanOperators">
            <schema>
                <ddl>create table alpha ( id integer, beta integer )</ddl>
                <ddl>create table gamma ( id integer not null, zooba integer )</ddl>
                <ddl>create table fargle ( id integer not null, dooba integer )</ddl>
            </schema>
            <testpoint testKind="dql" testName="TestAnd" testSQL="select * from alpha where id = 0 and id = 1" />
            <testpoint testKind="dql" testName="TestOr" testSQL="select * from alpha where id != 0 or id = 1" />
            <testpoint testKind="dql" testName="TestNot" testSQL="select * from alpha where not id != 0" />
            <testpoint testKind="dql" testName="TestPrecedenceNotAndL" testSQL='select * from alpha where not id != 0 and beta != 0' />
            <testpoint testKind="dql" testName="TestPrecedenceNotOrL" testSQL='select * from alpha where not id != 0 or beta != 0' />
            <testpoint testKind="dql" testName="TestPrecedenceNotAndR" testSQL='select * from alpha where id != 0 and not beta != 0' />
            <testpoint testKind="dql" testName="TestPrecedenceNotOrR" testSQL='select * from alpha where id != 0 or not beta != 0' />
            <testpoint testKind="dql" testName="TestPrecedenceOrOr" testSQL='select * from alpha where id != 0 or beta != 0 or beta !=  1' />
            <testpoint testKind="dql" testName="TestPrecedenceOrAnd" testSQL='select * from alpha where id != 0 or beta != 0 and beta != 1' />
            <!-- We need to be a bit careful here. HSQLDB seems to want to 
                 rearrange the expressions so that equality tests are done first.
                 This is mostly irrelevant to us, but it make our tests fail. We only use
                 equality and inequality tests. -->
            <testpoint testKind="dql" testName="TestPrecedenceAndAnd" testSQL='select * from alpha where id != 0 and beta != 0 and beta != 1' />
            <testpoint testKind="dql" testName="TestPrecedenceAndOr" testSQL='select * from alpha where id != 0 and beta != 0 or beta != 1' />
        </test>
        <test name="TestRelationalOperators" sourcefolder="tests/sqlparser/tests" classname="org.voltdb.sqlparser.TestRelationalOperators">
            <schema>
                <ddl>create table alpha ( id integer, beta integer )</ddl>
                <ddl>create table gamma ( id integer not null, zooba integer )</ddl>
                <ddl>create table fargle ( id integer not null, dooba integer )</ddl>
            </schema>
            <testpoint testKind="dql" testName="TestEq" testSQL="select * from alpha where id = 0" />
            <testpoint testKind="dql" testName="TestNotEq" testSQL="select * from alpha where id != 0" />
            <testpoint testKind="dql" testName="TestLessThan" testSQL="select * from alpha where id &lt; 0" />
            <testpoint testKind="dql" testName="TestLessEqual" testSQL="select * from alpha where id &lt;= 0" />
            <testpoint testKind="dql" testName="TestGreaterThan" testSQL="select * from alpha where id &gt; 0" />
            <testpoint testKind="dql" testName="TestGreaterEqual" testSQL="select * from alpha where id != 0" />
        </test>
        <test name="TestRelationalOperators" sourcefolder="tests/sqlparser/tests" classname="org.voltdb.sqlparser.TestRelationalOperators">
            <schema>
                <ddl>create table alpha ( id integer, beta integer )</ddl>
                <ddl>create table gamma ( id integer not null, zooba integer )</ddl>
                <ddl>create table fargle ( id integer not null, dooba integer )</ddl>
            </schema>
            <testpoint testKind="dql" testName="TestEq" testSQL="select * from alpha where id = 0" />
            <testpoint testKind="dql" testName="TestNotEq" testSQL="select * from alpha where id != 0" />
            <testpoint testKind="dql" testName="TestLessThan" testSQL="select * from alpha where id &lt; 0" />
            <testpoint testKind="dql" testName="TestLessEqual" testSQL="select * from alpha where id &lt;= 0" />
            <testpoint testKind="dql" testName="TestGreaterThan" testSQL="select * from alpha where id &gt; 0" />
            <testpoint testKind="dql" testName="TestGreaterEqual" testSQL="select * from alpha where id &gt;= 0" />
        </test>
        <test name="TestSimpleSQL" sourcefolder="tests/sqlparser/tests" classname="org.voltdb.sqlparser.TestSimpleSQL">
            <schema>
                <ddl>create table alpha ( id integer, beta integer )</ddl>
                <ddl>create table gamma ( id integer not null, zooba integer )</ddl>
                <ddl>create table fargle ( id integer not null, dooba integer )</ddl>
            </schema>
            <testpoint testKind="ddl" testName="testCreateTable" testSQL="create table alpha ( id integer not null, beta integer)" />
            <testpoint testKind="ddl" testName="testCreateTableWithDecimal" testSQL="create table alpha ( id integer not null, beta Decimal)" />
            <testpoint testKind="dml" testName="testInsert1" testSQL="insert into alpha values (1, 1)" />
            <testpoint testKind="dml" testName="testInsert2" testSQL="insert into alpha (beta, id) values (100, 101)" />
            <testpoint testKind="dql" testName="testSelectId" testSQL="select id from alpha" />
            <testpoint testKind="dql" testName="testSelectBeta" testSQL="select beta from alpha" />
            <testpoint testKind="dql" testName="testSelectFromFargle" testSQL="select dooba from fargle" />
            <testpoint testKind="dql" testName="testSelectFromGamma" testSQL="select id from gamma" />
            <testpoint testKind="dql" testName="testCaseSelect" testSQL="select ID from GAMMA" />
        </test>
        <test name="TestTableCreation" sourcefolder="tests/sqlparser/tests" classname="org.voltdb.sqlparser.TestTableCreation">
            <schema/>
            <testpoint testKind="ddl" testName="testCreateTableTinyInt" testSQL="create table alpha ( id TiNyInT not null, beta TINYINT)"
                comment="Test TINYINT type."/>
            <testpoint testKind="ddl" testName="testCreateTableSmallInt" testSQL="create table alpha ( id SmallInt not null, beta SMALLINT)"
                comment="Test SMALLINT type."/>
            <testpoint testKind="ddl" testName="testCreateTableInteger" testSQL="create table alpha ( id integer not null, beta integer)"
                comment="Test INTEGER type."/>
            <testpoint testKind="ddl" testName="testCreateTableBigInt" testSQL="create table alpha ( id BiGiNt not null, beta bIgInT)"
                comment="Test BIGINT type."/>
